const productos = [
    // GUITARRAS
    {
        id: "guitarra-01",
            nombre: "Fender Strato",
                imagen: "img/strato.jpg",
                    precio: 900,
                    cantidad: 1,
        },
    {
        id: "guitarra-02",
            nombre: "Fender Telecaster",
                imagen: "img/telecaster.jpg",
                    precio: 1000,
                    cantidad: 1,
        },
    {
        id: "guitarra-03",
            nombre: "Gibson Les Paul",
                imagen: "img/lespaul.jpg",
                    precio: 1200,
                    cantidad: 1,
        },
    {
        id: "guitarra-04",
            nombre: "Gibson SG",
                imagen: "img/guitarrasg.jpg",
                    precio: 1500,
                    cantidad: 1,
        },
    {
        id: "guitarra-05",
            nombre: "Yamaha C40",
                imagen: "img/acusticayamaha.jpg",
                    precio: 500,
                    cantidad: 1,
        },
    // BATERIAS
    {
        id: "bateria-01",
            nombre: "Mapex Saturn V",
                imagen: "img/mapexsaturnV.jpg",
                    precio: 3000,
                    cantidad: 1,
        },
    {
        id: "bateria-02",
            nombre: "DW Collectors",
                imagen: "img/dwcollectors.jpg",
                    precio: 4000,
                    cantidad: 1,
        },
    {
        id: "bateria-03",
            nombre: "Tama Starclassic",
                imagen: "img/tamastarclassic.jpg",
                    precio: 3000,
                    cantidad: 1,
        },
    {
        id: "bateria-04",
            nombre: "Pearl Masters",
                imagen: "img/pearlmasters.jpg",
                    precio: 2500,
                    cantidad: 1,
        },
    {
        id: "bateria-05",
            nombre: "Roland TD1",
                imagen: "img/rolandtd-1.jpg",
                    precio: 1500,
                    cantidad: 1,
        },
    {
        id: "bateria-06",
            nombre: "Roland SPD SX",
                imagen: "img/rolandsx.jpg",
                    precio: 1000,
                    cantidad: 1,
        },
    // BAJOS
    {
        id: "bajo-01",
            nombre: "Gibson Bass SG",
                imagen: "img/bajoSG.jpg",
                    precio: 2000,
                    cantidad: 1,
        },
    {
        id: "bajo-02",
            nombre: "Fender Jazz Bass",
                imagen: "img/fenderjazzbass.jpg",
                    precio: 2500,
                    cantidad: 1,
        },
    // TECLADOS 
    {
        id: "teclados-01",
            nombre: "Roland XPS10",
                imagen: "img/rolandXPS10.jpg",
                    precio: 1000,
                    cantidad: 1,
        },
    {
        id: "teclados-02",
            nombre: "Casio CTX 800",
                imagen: "img/casioctx800.jpg",
                    precio: 2000,
                    cantidad: 1,
        },
    {
        id: "teclados-03",
            nombre: "Behringer poly D",
                imagen: "img/behringerPOLyD.jpg",
                    precio: 1500,
                    cantidad: 1,
        },
    {
        id: "teclados-04",
            nombre: "Novation Mini Nova",
                imagen: "img/novationmininova.jpg",
                    precio: 1000,
                    cantidad: 1,
        }
    ]